name: Integration

on:
  workflow_dispatch:
  pull_request:
    branches: [ dev, main ]

jobs:
  restore-build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dotnet SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Output student name
      run: echo Alexander Boyle
     
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore
      
    - name: Build solution
      working-directory: ./src
      run: dotnet build
      
    - name: Run all tests
      working-directory: ./src
      run: dotnet test
      
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
